### ISSUE TITLE
Tests don't complete with 3.12

### ISSUE THREAD

**Issue by daveisfera** [Eittipat/pyrtmp#12]
It appears that [this change in the behavior of 3.12](https://github.com/python/cpython/issues/104344) is causing problems. My understanding of `asyncio` is limited, but it appears that the `reader` and/or `writer` need to be closed so `wait_for_closed` will complete and that's causing the tests to timeout

**Comment by Eittipat** [comment]
Thank you, I never tested with python 12 before. 
I plan to fix this bug in this weekend.

Thank you

**Comment by daveisfera** [comment]
I was able to figure out the fix and added it to #11
