### ISSUE TITLE
how to play live？after push the stream.

### ISSUE THREAD

**Issue by bird00101011** [Eittipat/pyrtmp#22]
how to play live？after push the stream.

**Comment by Eittipat** [comment]
Cannot play directly, this lib is mainly an adapter to convert rtmp stream
into something else. In order to play your stream, you can forward rtmp to
ffmpeg and generating hls play list and play it using hls player. Look at
"demo_ffmpeg.py"

**Comment by bird00101011** [comment]
Thank u.
