### ISSUE TITLE
Unknown CommandMessage

### ISSUE THREAD

**Issue by lixinlin** [Eittipat/pyrtmp#3]
when play use vlc, got below warning message , and cannot play the video with vlc( always black screen)
Unknown CommandMessage 'getStreamLength', use default parser
Unknown message CommandMessage(8,0,0,37,20,0,37)
Unknown NetStreamCommand 'play', use default parser
Unknown message NetStreamCommand(8,0,0,35,20,1,35)
Unknown CommandMessage '3', use default parser
Unknown message UserControlMessage(2,1,1,10,4,0,10)

**Comment by Eittipat** [comment]
Currently, pyrtmp does not support the playback feature (because I didn't use it)

I don't have any plan to implement this feature in the near future.
