### ISSUE TITLE
ImportError: cannot import name 'tokenparser' from 'bitstring'

### ISSUE THREAD

**Issue by imocat** [Eittipat/pyrtmp#8]
hello,

i install the pyrtmp and use.
the python response this message:

from bitstring import tokenparser, BitStream
ImportError: cannot import name 'tokenparser' from 'bitstring'

how can i fixit?

and pyrtmp version "pyrtmp-0.2.0"

tks

**Comment by Fede14it** [comment]
Same error

**Comment by Valdemayar** [comment]
I guess you downloaded this with pip. This problem solved but hasn't released at PyPI yet. 

Check out PR with solution:
https://github.com/Eittipat/pyrtmp/pull/7

**Comment by CyanChanges** [comment]
So when to upload

**Comment by Minuhy** [comment]
hello，you can use `pip install bitstring==3.1.9` command to fix it

**Comment by evra** [comment]
> hello，you can use `pip install bitstring==3.1.9` command to fix it

after installing this version of bitstring the pyrtmp server stops at `INFO:pyrtmp.messages:Handshake!` and doesn't proceed

Python 3.11.6
